blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DPYTHON_EXECUTABLE=/home/sean_hastings/anaconda3/envs/test/bin/python3.7
- -DPYTHON_INCLUDE_DIR=/home/sean_hastings/anaconda3/envs/test/include/python3.7m
- -DPYTHON_LIBRARY=/home/sean_hastings/anaconda3/envs/test/lib/libpython3.7m.so
devel_layout: linked
devel_space: devel
extend_path: null
install: true
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
